
import pathlib


# absolute path to snakemake dir
snakemake_dir = Path(workflow.snakefile).parent.resolve()
#sys.path.append(str(snakemake_dir/"scripts"))
#import utils

# include default config values
configfile: f"{snakemake_dir}/config/default_config.yaml"


include: "rules/sample_table.smk"
include: "rules/strainGE.smk"
include: "rules/strainGR.smk"


if "genera" not in config:
    raise Exception("You need to define one or several genera in the config file")

genera = config["genera"]
if type(genera) == str:
    Genus_of_interest = [genera]
else:
    Genus_of_interest = list(genera)








rule all_strainGST: 
    input: 
        expand("StrainGST_{genus}.tsv", genus= Genus_of_interest),
        expand("Intermediate_files/{genus}/StrainGR/all_finished", genus= Genus_of_interest),
        


rule all_create_db:
    expand("{genus}-db.hdf5", genus= Genus_of_interest)



rule all:
    input:
        "StrainGR_compare_{genus}_finished"
    
